# Neural Networks from Scratch with Python from the youtube channel sentdex <br />

"The goal is to break it down so much that it is panfully simple "


#### Episodes


* [Neural Networks from Scratch - P.1 Intro and Neuron Code:](https://www.youtube.com/watch?v=Wo5dMEP_BbI)
* [Neural Networks from Scratch - P.2 Coding a Layer:](https://www.youtube.com/watch?v=lGLto9Xd7bU)
* [Neural Networks from Scratch - P.3 The Dot Product:](https://www.youtube.com/watch?v=tMrbN67U9d4)
* [Neural Networks from Scratch - P.4 Batches, Layers, and Objects:](https://www.youtube.com/watch?v=TEWy9vZcxW4)



# Objective: 

Learn about Neural Networks from Scratch with Python .



# Introduction: 
The purpuse is to know how neural networks works at a very deep level, because trying to solve more complex problems is gonna require a deep understand of how things actually work.

In [3]:
import numpy as np

inputs =[[1,2,3,2.5]
         ,[2.0,5.0,-1.0,2.0]
         ,[1.5,2.7,3.3,-0.8]]
         
         
weights = [[0.2,  0.8 ,-0.5,  1.0]
          ,[0.5, -0.91, 0.26,-0.5]
          ,[-0.26,-0.27, 0.17,0.87]]
 
biases =[2,3,0.5]

weights2 = [[0.1,  -0.14 ,-0.5]
          ,[-0.5, 0.12, -0.33]
          ,[-0.44,0.73,-0.13]]
 
biases2 =[-1,2,-0.5]


layer1_outputs = np.dot(inputs,np.array(weights).T) +biases
print( layer1_outputs ) 
layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) +biases2
layer2_outputs

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 2.01   2.551 -0.754]]


array([[-1.8819 , -1.04185, -2.03875],
       [ 0.0434 , -2.7332 , -5.7633 ],
       [-0.77914,  1.54994,  0.57585]])